### ISSUE TITLE
Setup Kanban Board - Ruby Group Capstone Project

### ISSUE THREAD

**Issue by AmanWorku** [AmanWorku/Catalog-Ruby#22]
## Hello 
![](https://media.giphy.com/media/Cmr1OMJ2FN0B2/giphy.gif)
- In this capstone project we are teams of `2`.
- List of the activities assigned to members:
  - `Team Member #1`  => @AmanWorku 
  - `Team Member #2` => @Salwa99

**Comment by Abenezer-Tilahun** [comment]
Hi @AmanWorku @Salwa99 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ Good Job for Provide the link to GitHub project
✔️ Good Job for the Mention the number of people in the group
✔️ Good job for Implemented Ruby group capstone: set up your Kanban board.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
